# Generated by Django 3.0.2 on 2020-01-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ci',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.FloatField(),
        ),
    ]
