# Generated by Django 3.0.2 on 2020-01-27 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
