# Generated by Django 3.0.2 on 2020-01-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200126_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='gender',
            new_name='gender_id',
        ),
    ]
