# Generated by Django 3.0.2 on 2020-01-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200126_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='gender_id',
            new_name='gender',
        ),
    ]
